### ISSUE TITLE
Allow config for work in progress title

### ISSUE THREAD

**Issue by SeanReece** [SeanReece/pr-reporter-slack#4]
We use `[WIP]` in the PR title to mark that a PR is work in progress, but I'm sure other repos have different conventions. We should allow users to configure what flag they use to mark a work in progress PR.

Something like 
```yaml
inputs:
  wip-tag:
    description: 'The string used in PR titles to mark a Work-In-Progress PR'
    required: false
    default: '[WIP]'
```
