### ISSUE TITLE
Config to disable WIP/draft PR ignore

### ISSUE THREAD

**Issue by SeanReece** [SeanReece/pr-reporter-slack#6]
Currently, pr-reporter-slack ignores draft PRs and PRs marked with `[WIP]`. Should allow user to configure this to message about ALL PRs

Maybe:

```yaml
inputs:
  ignore-wip:
    description: 'Should pr-reporter-slack ignore work-in-progress PRs'
    required: false
    default: true
```
