### ISSUE TITLE
Config to ignore dependabot

### ISSUE THREAD

**Issue by SeanReece** [SeanReece/pr-reporter-slack#7]
Github's dependabot can create a lot of PRs, should add a config to allow ignoring dependabot.

```yaml
inputs:
  ignore-dependabot:
    description: 'Should pr-reporter-slack ignore dependabot PRs'
    required: false
    default: false
```
