### ISSUE TITLE
Config to disable no PR message

### ISSUE THREAD

**Issue by SeanReece** [SeanReece/pr-reporter-slack#8]
Currently pr-reporter-slack will send still send a message when there are no PRs awaiting review with something like "👍Good work! There's no PRs awaiting review"

Allow user to disable this for their repo. This would be helpful for smaller repos with less frequent PRs.

```yaml
inputs:
  send-empty:
    description: 'Should send message when there are no PRs awaiting review'
    required: false
    default: true
```
